### ISSUE TITLE
Plants#1: Грамматическая ошибка.

### ISSUE THREAD

**Issue by DragonRomeo** [rolling-scopes-school/checklist#43]
PLANTS#1
>Интерактивность, реализуемая через css
>иконки соцсетей в футере при нажатии на них ведут на гитхаб автора проекта и на страницу курса (допускается доабвление своих вариантов иконок github или RSSchool) https://rs.school/js-stage0/
> '**доабвление**'
![image](https://user-images.githubusercontent.com/74453874/211316415-49cd4e40-dfe4-4884-86b5-e4433331841f.png)

(Некритично, но вдруг)

**Comment by WiiJoy** [comment]
fixed
